# -*- coding: utf-8 -*-
"""Graded_Task_10_LSTM_BM_CM (2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ki3AEK2lgslbJndD6K2UI8ilIi5wgez

Consider the following english_sentences along with their corresponding labels(french_sentences).
Train the LSTM on the given data and predict on the model.
"""

import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Model
from tensorflow.keras.layers import LSTM, Embedding, Dense, TimeDistributed, Dropout, Bidirectional, Input
sentences = [ "I love machine learning",
    "TensorFlow is a powerful tool",
    "Translate this sentence",
    "Artificial intelligence is changing the world",
    "Python is a versatile programming language",
    "Can you solve this problem?",
    "Data science involves analyzing large datasets",
    "The internet has revolutionized communication",
    "I enjoy reading science fiction novels",
    "Coding is an essential skill in today's world",
    "Machine learning algorithms can predict outcomes",
    "Climate change is a pressing global issue",
    "Please pass me the salt and pepper",
    "The universe is vast and mysterious",
    "Learning a new language enhances cognitive abilities",
    "Robots are becoming increasingly sophisticated",
    "The stock market can be unpredictable",
    "Mobile phones have become indispensable",
    "Artists express themselves through their work",
    "Quantum physics explores the nature of reality",
    "Global collaboration is key for solving challenges",
    "The Earth rotates on its axis",
    "Virtual reality provides immersive experiences",
    "Reading books broadens one's perspective",
    "Renewable energy is crucial for sustainability",
    "A healthy diet is essential for well-being",
    "Space exploration opens new frontiers",
    "The Renaissance was a period of cultural revival",
    "Solving puzzles enhances problem-solving skills",
    "Music has the power to evoke emotions",
    "The human brain is a remarkable organ",
    "Innovation drives technological advancements",
    "Cats and dogs make wonderful companions",
    "The Great Wall of China is a marvel of engineering",
    "Einstein's theory of relativity revolutionized physics",
    "Positive thinking contributes to mental well-being",
    "The internet of things connects devices globally",
    "Biodiversity is crucial for ecosystem health",
    "Exploring nature has therapeutic benefits",
    "Mathematics is the language of the universe",
    "Programming is a valuable skill in the digital age",
    "The Renaissance era gave birth to great art and ideas",
    "A healthy lifestyle includes regular exercise",
    "Cryptocurrency is changing the landscape of finance",
    "Sustainable practices are crucial for environmental conservation",
    "The Industrial Revolution transformed manufacturing processes",
    "Effective communication is key in any relationship",
    "History provides valuable lessons for the future",
    "The importance of education cannot be overstated",
    "Genetic diversity is essential for species survival",
    "Traveling broadens one's cultural understanding",
    "The concept of time is a fascinating philosophical topic",
    "Epidemiology plays a vital role in public health",
    "Meditation has proven benefits for mental well-being",
    "Space exploration sparks curiosity about the cosmos",
    "Bilingualism enhances cognitive flexibility",
    "The impact of automation on employment is a debated topic",
    "Challenges foster personal growth and resilience",
    "Ancient civilizations left behind remarkable architectural wonders",
    "The scientific method is a systematic approach to inquiry",
    "Critical thinking is an essential skill for problem-solving",
    "The human genome project revolutionized genetics",
    "Cultural diversity enriches society",
    "Renewable energy sources are a sustainable solution",
    "The concept of artificial intelligence dates back centuries",
    "Reading fosters imagination and creativity",
    "Physics seeks to understand the fundamental laws of the universe",
    "The importance of water conservation is emphasized globally",
    "Philosophy explores fundamental questions about existence",
    "Adaptability is a valuable trait in a rapidly changing world",
    "The butterfly effect illustrates the interconnectedness of events",
    "Ecotourism promotes responsible travel and conservation",
    "Cognitive dissonance explores the discomfort of conflicting beliefs",
    "The concept of beauty varies across cultures",
    "Nanotechnology has promising applications in various fields",
    "Oceanography studies the mysteries of the world's oceans",
    "The placebo effect highlights the mind-body connection",
    "Environmental sustainability is a collective responsibility",
    "The impact of social media on society is a subject of debate",
    "Culinary arts blend creativity and precision",
    "Nuclear fusion holds potential for clean energy production",
    "The role of women in history often goes unrecognized",
    "Biotechnology advancements offer promising medical breakthroughs",
    "The concept of time travel captivates the human imagination",
    "Mathematical models help us understand complex phenomena",
    "Theories of consciousness delve into the nature of self-awareness",
             ]

labels = [ "J'adore l'apprentissage automatique",
    "TensorFlow est un outil puissant",
    "Traduisez cette phrase",
    "L'intelligence artificielle change le monde",
    "Python est un langage de programmation polyvalent",
    "Pouvez-vous résoudre ce problème ?",
    "La science des données implique l'analyse de grands ensembles de données",
    "Internet a révolutionné la communication",
    "J'aime lire des romans de science-fiction",
    "Coder est une compétence essentielle dans le monde d'aujourd'hui",
    "Les algorithmes d'apprentissage automatique peuvent prédire des résultats",
    "Le changement climatique est un problème mondial pressant",
    "S'il vous plaît, passez-moi le sel et le poivre",
    "L'univers est vaste et mystérieux",
    "Apprendre une nouvelle langue améliore les capacités cognitives",
    "Les robots deviennent de plus en plus sophistiqués",
    "La bourse peut être imprévisible",
    "Les téléphones portables sont devenus indispensables",
    "Les artistes s'expriment à travers leur travail",
    "La physique quantique explore la nature de la réalité",
    "La collaboration mondiale est essentielle pour résoudre les défis",
    "La Terre tourne sur son axe",
    "La réalité virtuelle offre des expériences immersives",
    "Lire des livres élargit la perspective",
    "L'énergie renouvelable est cruciale pour la durabilité",
    "Une alimentation saine est essentielle pour le bien-être",
    "L'exploration spatiale ouvre de nouvelles frontières",
    "La Renaissance fut une période de renouveau culturel",
    "Résoudre des puzzles améliore les compétences en résolution de problèmes",
    "La musique a le pouvoir d'évoquer des émotions",
    "Le cerveau humain est un organe remarquable",
    "L'innovation stimule les progrès technologiques",
    "Les chats et les chiens font d'excellents compagnons",
    "La Grande Muraille de Chine est une merveille d'ingénierie",
    "La théorie de la relativité d'Einstein a révolutionné la physique",
    "La pensée positive contribue au bien-être mental",
    "Internet des objets connecte des appareils à l'échelle mondiale",
    "La biodiversité est cruciale pour la santé des écosystèmes",
    "Explorer la nature a des bienfaits thérapeutiques",
    "Les mathématiques sont le langage de l'univers",
    "La programmation est une compétence précieuse à l'ère numérique",
    "L'époque de la Renaissance a donné naissance à de grandes œuvres d'art et d'idées",
    "Un mode de vie sain inclut une pratique régulière de l'exercice",
    "Les cryptomonnaies changent le paysage financier",
    "Les pratiques durables sont cruciales pour la conservation de l'environnement",
    "La Révolution industrielle a transformé les processus de fabrication",
    "La communication efficace est essentielle dans toute relation",
    "L'histoire offre des leçons précieuses pour l'avenir",
    "L'importance de l'éducation ne peut être surestimée",
    "La diversité génétique est essentielle à la survie des espèces",
    "Les voyages élargissent la compréhension culturelle",
    "Le concept du temps est un sujet philosophique fascinant",
    "L'épidémiologie joue un rôle vital dans la santé publique",
    "La méditation a des bienfaits prouvés pour le bien-être mental",
    "L'exploration spatiale suscite la curiosité sur le cosmos",
    "Le bilinguisme améliore la flexibilité cognitive",
    "L'impact de l'automatisation sur l'emploi est un sujet débattu",
    "Les défis favorisent la croissance personnelle et la résilience",
    "Les anciennes civilisations ont laissé derrière elles d'étonnantes merveilles architecturales",
    "La méthode scientifique est une approche systématique de l'enquête",
    "La pensée critique est une compétence essentielle pour la résolution de problèmes",
    "Le projet du génome humain a révolutionné la génétique",
    "La diversité culturelle enrichit la société",
    "Les sources d'énergie renouvelable sont une solution durable",
    "Le concept d'intelligence artificielle remonte à plusieurs siècles",
    "La lecture favorise l'imagination et la créativité",
    "La physique cherche à comprendre les lois fondamentales de l'univers",
    "L'importance de la conservation de l'eau est soulignée à l'échelle mondiale",
    "La philosophie explore des questions fondamentales sur l'existence",
    "L'adaptabilité est une qualité précieuse dans un monde en rapide évolution",
    "L'effet papillon illustre l'interconnexion des événements",
    "L'écotourisme promeut un voyage responsable et la conservation",
    "La dissonance cognitive explore le malaise des croyances contradictoires",
    "Le concept de beauté varie selon les cultures",
    "Les nanotechnologies offrent des applications prometteuses dans divers domaines",
    "L'océanographie étudie les mystères des océans du monde",
    "L'effet placebo met en lumière la connexion esprit-corps",
    "La durabilité environnementale est une responsabilité collective",
    "L'impact des médias sociaux sur la société est un sujet de débat",
    "Les arts culinaires allient créativité et précision",
    "La fusion nucléaire offre un potentiel pour la production d'énergie propre",
    "Le rôle des femmes dans l'histoire est souvent méconnu",
    "Les avancées en biotechnologie offrent des percées médicales prometteuses",
    "Le concept du voyage dans le temps captive l'imagination humaine",
    "Les modèles mathématiques nous aident à comprendre des phénomènes complexes",
    "Les théories de la conscience explorent la nature de la prise de conscience de soi", ]


word_tokenizer = Tokenizer(lower=False, filters='')
word_tokenizer.fit_on_texts(sentences)
X = word_tokenizer.texts_to_sequences(sentences)
max_len = max([len(sentence) for sentence in X])
X = pad_sequences(X, maxlen=max_len, padding='post')
label_tokenizer = Tokenizer(lower=False)
label_tokenizer.fit_on_texts(labels)
y = label_tokenizer.texts_to_sequences(labels)
y = pad_sequences(y, maxlen=max_len, padding='post')
y = [to_categorical(i, num_classes=len(label_tokenizer.word_index) + 1) for i in y]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)
input_word = Input(shape=(max_len,))
model = Embedding(input_dim=len(word_tokenizer.word_index) + 1, output_dim=50, input_length=max_len)(input_word)
model = Dropout(0.1)(model)
model = Bidirectional(LSTM(units=100, return_sequences=True, recurrent_dropout=0.1))(model)
out = TimeDistributed(Dense(len(label_tokenizer.word_index) + 1, activation="softmax"))(model)

model = Model(input_word, out)
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

model.fit(X_train, np.array(y_train), batch_size=32, epochs=5, validation_split=0.1, verbose=1)

loss, accuracy = model.evaluate(X_test, np.array(y_test), verbose=0)
print(f"Test Accuracy: {accuracy}")

new_sentence = ["Aisha traveled to Islamabad last summer."]
new_X = word_tokenizer.texts_to_sequences(new_sentence)
new_X = pad_sequences(new_X, maxlen=max_len, padding='post')
predictions = model.predict(new_X)

predicted_labels = np.argmax(predictions, axis=-1)
labels = [label_tokenizer.index_word[label] for label in predicted_labels[0] if label != 0]
print(labels)

len(english_sentences)

len(french_sentences)

